version: "3.7"
services:
  gem:
    container_name: track-record-dev
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "while [ true ]; do sleep 10; done"
    tty: true
    stdin_open: true
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - .:/track-record/
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: track-record-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      xpack.monitoring.enabled: "true"
    ports:
      - 9200:9200
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    container_name: track-record-kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    hostname: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    expose:
      - 5601
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
